//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecursosHumanos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empleado
    {
        public int Id { get; set; }
        public int Codigo_Empleado { get; set; }
        public string Nombre { get; set; }
        public string Apellido { get; set; }
        public string Telefono { get; set; }
        public int Departamento { get; set; }
        public int Cargo { get; set; }
        public System.DateTime Fecha_Ingreso { get; set; }
        public decimal Salario { get; set; }
        public bool Estatus { get; set; }
    
        public virtual Cargo Cargo1 { get; set; }
        public virtual Departamento Departamento1 { get; set; }
    }
}
